//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demos {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class marker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal marker() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demos.marker", typeof(marker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Check_C {
            get {
                return ResourceManager.GetString("Check_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Data_C {
            get {
                return ResourceManager.GetString("Data_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable/Disable External /START Trigger과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string External__START_DESC {
            get {
                return ResourceManager.GetString("External /START_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External /START과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string External__START_DISP {
            get {
                return ResourceManager.GetString("External /START_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RTC List Type. Single buffer or Auto(or Double) buffer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string List_type_DESC {
            get {
                return ResourceManager.GetString("List type_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string List_type_DISP {
            get {
                return ResourceManager.GetString("List type_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max. Time to Measurement (sec)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MaxMeasureTime_DESC {
            get {
                return ResourceManager.GetString("MaxMeasureTime_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MaxMeasureTime_DISP {
            get {
                return ResourceManager.GetString("MaxMeasureTime_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Measurement과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Measurement_C {
            get {
                return ResourceManager.GetString("Measurement_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plot as Graph After Finish to Mark. Create Measurement Begin, End Entities과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plot_DESC {
            get {
                return ResourceManager.GetString("Plot_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plot과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plot_DISP {
            get {
                return ResourceManager.GetString("Plot_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Scanner Position Acknowledge Status Before Start Mark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Position_DESC {
            get {
                return ResourceManager.GetString("Position_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position Ack과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Position_DISP {
            get {
                return ResourceManager.GetString("Position_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Scanner Power Ok Status Before Start Mark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Power_DESC {
            get {
                return ResourceManager.GetString("Power_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Supply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Power_DISP {
            get {
                return ResourceManager.GetString("Power_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Entity(MeasurementBegin) for Measurement Session과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Session_DESC {
            get {
                return ResourceManager.GetString("Session_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Session_DISP {
            get {
                return ResourceManager.GetString("Session_DISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check Scanner Temperature Ok Status Before Start Mark과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Temp_DESC {
            get {
                return ResourceManager.GetString("Temp_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Temp_DISP {
            get {
                return ResourceManager.GetString("Temp_DISP", resourceCulture);
            }
        }
    }
}
