//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 3D.
        /// </summary>
        public static string Calibration3D {
            get {
                return ResourceManager.GetString("Calibration3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Block.
        /// </summary>
        public static string ConvertBlock {
            get {
                return ResourceManager.GetString("ConvertBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard are empty. Please copy or cut at first..
        /// </summary>
        public static string DocumentClipboardEmpty {
            get {
                return ResourceManager.GetString("DocumentClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset encoder values ?.
        /// </summary>
        public static string DocumentEncoderReset {
            get {
                return ResourceManager.GetString("DocumentEncoderReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to new document without save ?.
        /// </summary>
        public static string DocumentNew {
            get {
                return ResourceManager.GetString("DocumentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to open without save ?.
        /// </summary>
        public static string DocumentOpen {
            get {
                return ResourceManager.GetString("DocumentOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explode.
        /// </summary>
        public static string Explode {
            get {
                return ResourceManager.GetString("Explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to extract points cloud from {0}..
        /// </summary>
        public static string ExtractPointsCloudFailed {
            get {
                return ResourceManager.GetString("ExtractPointsCloudFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to extract points cloud from {0} ?.
        /// </summary>
        public static string ExtractPointsCloudTrying {
            get {
                return ResourceManager.GetString("ExtractPointsCloudTrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help - Keyboards.
        /// </summary>
        public static string HelpKeboard {
            get {
                return ResourceManager.GetString("HelpKeboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heuristic algorithm has failed !.
        /// </summary>
        public static string HeuristicFailed {
            get {
                return ResourceManager.GetString("HeuristicFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB license key is not founded..
        /// </summary>
        public static string LicenseKeyIsNotFounded {
            get {
                return ResourceManager.GetString("LicenseKeyIsNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information within USB license key..
        /// </summary>
        public static string LicenseKeyWithoutIformation {
            get {
                return ResourceManager.GetString("LicenseKeyWithoutIformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker status is busy now !.
        /// </summary>
        public static string MarkerIsBusy {
            get {
                return ResourceManager.GetString("MarkerIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start mark ?.
        /// </summary>
        public static string MarkerTryingToStart {
            get {
                return ResourceManager.GetString("MarkerTryingToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for external /START trigger ....
        /// </summary>
        public static string MarkerWaitingExternalStart {
            get {
                return ResourceManager.GetString("MarkerWaitingExternalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select target parent entity to layer..
        /// </summary>
        public static string NoParentWhenActInsert {
            get {
                return ResourceManager.GetString("NoParentWhenActInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Optimizer.
        /// </summary>
        public static string PathOptimizer {
            get {
                return ResourceManager.GetString("PathOptimizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Cloud.
        /// </summary>
        public static string PointsCloud {
            get {
                return ResourceManager.GetString("PointsCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted data size are {0} and base location at {1}..
        /// </summary>
        public static string PopUpOptimizedSize {
            get {
                return ResourceManager.GetString("PopUpOptimizedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start power compensate ?.
        /// </summary>
        public static string PowerCompensateStart {
            get {
                return ResourceManager.GetString("PowerCompensateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Map.
        /// </summary>
        public static string PowerMap {
            get {
                return ResourceManager.GetString("PowerMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powermap is busy now..
        /// </summary>
        public static string PowerMapBusy {
            get {
                return ResourceManager.GetString("PowerMapBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start power mapping ?.
        /// </summary>
        public static string PowerMapStart {
            get {
                return ResourceManager.GetString("PowerMapStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to set category: {0} as 1:1 ?.
        /// </summary>
        public static string PowerMapToReset {
            get {
                return ResourceManager.GetString("PowerMapToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear all categories ?.
        /// </summary>
        public static string PowerMapTryingToClear {
            get {
                return ResourceManager.GetString("PowerMapTryingToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start power verification ?.
        /// </summary>
        public static string PowerVerifyStart {
            get {
                return ResourceManager.GetString("PowerVerifyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control.
        /// </summary>
        public static string RemoteControl {
            get {
                return ResourceManager.GetString("RemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to switch &apos;LOCAL&apos; mode ?.
        /// </summary>
        public static string RemoteToLocal {
            get {
                return ResourceManager.GetString("RemoteToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to switch &apos;REMOTE&apos; mode ?.
        /// </summary>
        public static string RemoteToRemote {
            get {
                return ResourceManager.GetString("RemoteToRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        public static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c)SpiralLAB.
        /// </summary>
        public static string SpiralLab {
            get {
                return ResourceManager.GetString("SpiralLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s Empty key..
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue anyway ?.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target counts: {0}.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range: {0:F3} ~ {1:F3}W with {2} steps..
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target counts: {0}.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many nodes: {0}.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert to block ?.
        /// </summary>
        public static string TreeViewBlock {
            get {
                return ResourceManager.GetString("TreeViewBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create new scanner field correction file ?.
        /// </summary>
        public static string TreeViewCalibration3D {
            get {
                return ResourceManager.GetString("TreeViewCalibration3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to explode {0} ?.
        /// </summary>
        public static string TreeViewExplode {
            get {
                return ResourceManager.GetString("TreeViewExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert to group ?.
        /// </summary>
        public static string TreeViewGroup {
            get {
                return ResourceManager.GetString("TreeViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reverse {0} ?.
        /// </summary>
        public static string TreeViewReverse {
            get {
                return ResourceManager.GetString("TreeViewReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to show all children nodes ?.
        /// </summary>
        public static string TreeViewTooManyNodes {
            get {
                return ResourceManager.GetString("TreeViewTooManyNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
