//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration 3D.
        /// </summary>
        internal static string Calibration3D {
            get {
                return ResourceManager.GetString("Calibration3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Block.
        /// </summary>
        internal static string ConvertBlock {
            get {
                return ResourceManager.GetString("ConvertBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard are empty. Please copy or cut at first..
        /// </summary>
        internal static string DocumentClipboardEmpty {
            get {
                return ResourceManager.GetString("DocumentClipboardEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to reset encoder values ?.
        /// </summary>
        internal static string DocumentEncoderReset {
            get {
                return ResourceManager.GetString("DocumentEncoderReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to new document without save ?.
        /// </summary>
        internal static string DocumentNew {
            get {
                return ResourceManager.GetString("DocumentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to open without save ?.
        /// </summary>
        internal static string DocumentOpen {
            get {
                return ResourceManager.GetString("DocumentOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENC X,0: {0:F3}˚ [{1}].
        /// </summary>
        internal static string EncoderAngular {
            get {
                return ResourceManager.GetString("EncoderAngular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENC XY: {0:F3}, {1:F3}mm [{2}, {3}].
        /// </summary>
        internal static string EncoderXY {
            get {
                return ResourceManager.GetString("EncoderXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explode.
        /// </summary>
        internal static string Explode {
            get {
                return ResourceManager.GetString("Explode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to extract points cloud from {0}..
        /// </summary>
        internal static string ExtractPointsCloudFailed {
            get {
                return ResourceManager.GetString("ExtractPointsCloudFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to extract points cloud from {0} ?.
        /// </summary>
        internal static string ExtractPointsCloudTrying {
            get {
                return ResourceManager.GetString("ExtractPointsCloudTrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help - Keyboards.
        /// </summary>
        internal static string HelpKeboard {
            get {
                return ResourceManager.GetString("HelpKeboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heuristic algorithm has failed !.
        /// </summary>
        internal static string HeuristicFailed {
            get {
                return ResourceManager.GetString("HeuristicFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB license key is not founded..
        /// </summary>
        internal static string LicenseKeyIsNotFounded {
            get {
                return ResourceManager.GetString("LicenseKeyIsNotFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information within USB license key.
        ///It&apos;s Empty key..
        /// </summary>
        internal static string LicenseKeyWithoutIformation {
            get {
                return ResourceManager.GetString("LicenseKeyWithoutIformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  LOCAL .
        /// </summary>
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker status is busy now !.
        /// </summary>
        internal static string MarkerIsBusy {
            get {
                return ResourceManager.GetString("MarkerIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start mark ?.
        /// </summary>
        internal static string MarkerTryingToStart {
            get {
                return ResourceManager.GetString("MarkerTryingToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for external /START trigger ....
        /// </summary>
        internal static string MarkerWaitingExternalStart {
            get {
                return ResourceManager.GetString("MarkerWaitingExternalStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select target parent entity to layer..
        /// </summary>
        internal static string NoParentWhenActInsert {
            get {
                return ResourceManager.GetString("NoParentWhenActInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path Optimizer.
        /// </summary>
        internal static string PathOptimizer {
            get {
                return ResourceManager.GetString("PathOptimizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points Cloud.
        /// </summary>
        internal static string PointsCloud {
            get {
                return ResourceManager.GetString("PointsCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted data size are {0} and base location at {1}.
        ///Do you want to continue anyway ?.
        /// </summary>
        internal static string PopUpOptimizedSize {
            get {
                return ResourceManager.GetString("PopUpOptimizedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start power compensate ?
        ///Target counts: {0}.
        /// </summary>
        internal static string PowerCompensateStart {
            get {
                return ResourceManager.GetString("PowerCompensateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Map.
        /// </summary>
        internal static string PowerMap {
            get {
                return ResourceManager.GetString("PowerMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powermap is busy now..
        /// </summary>
        internal static string PowerMapBusy {
            get {
                return ResourceManager.GetString("PowerMapBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start power mapping ?
        ///Range: {0:F3} ~ {1:F3}W with {2} steps..
        /// </summary>
        internal static string PowerMapStart {
            get {
                return ResourceManager.GetString("PowerMapStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to set category: {0} as 1:1 ?.
        /// </summary>
        internal static string PowerMapToReset {
            get {
                return ResourceManager.GetString("PowerMapToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to clear all categories ?.
        /// </summary>
        internal static string PowerMapTryingToClear {
            get {
                return ResourceManager.GetString("PowerMapTryingToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to start power verification ?
        ///Target counts: {0}.
        /// </summary>
        internal static string PowerVerifyStart {
            get {
                return ResourceManager.GetString("PowerVerifyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bound (WHD): {0}.
        /// </summary>
        internal static string PropertyGridBound {
            get {
                return ResourceManager.GetString("PropertyGridBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Bound (WHD). Min: {0}, Max {1}, Center: {2}.
        /// </summary>
        internal static string PropertyGridRealBound {
            get {
                return ResourceManager.GetString("PropertyGridRealBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  REMOTE .
        /// </summary>
        internal static string Remote {
            get {
                return ResourceManager.GetString("Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  CONNECTED .
        /// </summary>
        internal static string RemoteConnected {
            get {
                return ResourceManager.GetString("RemoteConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control.
        /// </summary>
        internal static string RemoteControl {
            get {
                return ResourceManager.GetString("RemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DISCONNECTED .
        /// </summary>
        internal static string RemoteDisconnected {
            get {
                return ResourceManager.GetString("RemoteDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to switch &apos;LOCAL&apos; mode ?.
        /// </summary>
        internal static string RemoteToLocal {
            get {
                return ResourceManager.GetString("RemoteToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to switch &apos;REMOTE&apos; mode ?.
        /// </summary>
        internal static string RemoteToRemote {
            get {
                return ResourceManager.GetString("RemoteToRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse.
        /// </summary>
        internal static string Reverse {
            get {
                return ResourceManager.GetString("Reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c)SpiralLAB.
        /// </summary>
        internal static string SpiralLab {
            get {
                return ResourceManager.GetString("SpiralLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert to block ?.
        /// </summary>
        internal static string TreeViewBlock {
            get {
                return ResourceManager.GetString("TreeViewBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create new scanner field correction file ?.
        /// </summary>
        internal static string TreeViewCalibration3D {
            get {
                return ResourceManager.GetString("TreeViewCalibration3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children: {0}.
        /// </summary>
        internal static string TreeViewChildren {
            get {
                return ResourceManager.GetString("TreeViewChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to explode {0} ?.
        /// </summary>
        internal static string TreeViewExplode {
            get {
                return ResourceManager.GetString("TreeViewExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert to group ?.
        /// </summary>
        internal static string TreeViewGroup {
            get {
                return ResourceManager.GetString("TreeViewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID: {0}.
        /// </summary>
        internal static string TreeViewID {
            get {
                return ResourceManager.GetString("TreeViewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reverse {0} ?.
        /// </summary>
        internal static string TreeViewReverse {
            get {
                return ResourceManager.GetString("TreeViewReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to show all children nodes ?
        ///Too many nodes: {0}.
        /// </summary>
        internal static string TreeViewTooManyNodes {
            get {
                return ResourceManager.GetString("TreeViewTooManyNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
